### PR TITLE
Corrected README.md

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Fixed Grammatical errors

### CODE REVIEW

**Review by satyamz — APPROVED** [review]
lgtm

**Comment by satyamz** [comment]
@vipulgupta2048 can you write proper commit message?

**Comment by vipulgupta2048** [comment]
@satyamz I didn't clone the repo for this PR, I just edited it through GitHub. Hence the commit message can't be changed.

**Comment by satyamz** [comment]
@vipulgupta2048 thanks for the PR. But make sure next time you clone the repo. its not good practice to edit files on the Github as long as you know how to work with on Github.

**Comment by NisantaSahoo** [comment]
Congratulations @vipulgupta2048  for your PR getting merged! Thanks for taking part in OpenEBS Hackfest.
Fill up the doc form to get the Hackfest T-Shirt and Swags
https://docs.google.com/spreadsheets/d/1TZYIdERnD72YPeUsdS5hDfI6xgXXCax4-DHpXh-o6r0/edit?usp=sharing
Looking for some more awesome contributions from you and win more prizes

**Pull request merged**
